### ISSUE TITLE
A bunch of new matches

### ISSUE THREAD

**Issue by rszabo** [StanAngeloff/php.vim#27]
Hello.

I'm not accustomed to the way pull requests are made here so I'm sharing some changes I made locally. 

These changes add proper handling of class constants and static methods and -variables, makes null/array/boolean separate types and more.

Remember to add the keywords to "syn cluster" or else they aren't exported properly.

syn match phpStaticSelector "::" contained display

syn match phpClassConstant  "::\h\w*[^(]\w" contained contains=phpMethods,phpStaticSelector display
syn match phpStaticMethods  "::\h\w*(" contained contains=phpMethods,phpStaticSelector display
syn match phpStaticClasses "\v\h\w+(::)@=" contained display
syn keyword phpException DomainException BadFunctionCallException BadMethodCallException InvalidArgumentException OutOfBoundsException OutOfRangeException OverflowException UnderflowException UnexpectedValueException UserException RuntimeException LogicException ErrorException DOMException ReflectionException Exception contained

syn keyword phpArray array contained
syn keyword phpBoolean true false TRUE FALSE contained
syn keyword phpNull null NULL contained

" Default links
hi def link phpBoolean          Boolean
hi def link phpNull             Null
hi def link phpArray            Array

Furthermore, I strongly suggest adding file\|class\|brief\|details\|author\|created\|date\|todo\|bug\|warning\| to the list of phpDocTags.

**Comment by StanAngeloff** [comment]
Hey, I am archiving this discussion as it has gotten quite old now and hasn't seen any updated in over an year. If you have anything new to report, please feel free to reopen with more information. Thanks!

**Comment by rszabo** [comment]
Hi there!

Have you tried this with nvim, any recent version? I.e. NVIM 0.1.0 (compiled Nov  5 2015 00:37:23) / Commit: v0.1.0

Several of these matches that existed while we were working on this are no longer usable, i.e. phpStaticClasses, phpStaticClassVariable, phpStaticMethods.

 
syn match phpClassConstant  "::\h\w*[^(]\w" contained contains=phpMethods,phpStaticSelector display    
syn match phpStaticMethods  "::\(\h\w\+\)("me=e-1 contained contains=phpStaticSelector display      
syn match phpStaticClassVariable  "::\$\(\h\w\+\)" contained contains=phpStaticSelector display


Thank you

**Comment by StanAngeloff** [comment]
Hey @rszabo, the functionality in question wasn't merged in this repository. I had left you some feedback in my [earlier post](https://github.com/StanAngeloff/php.vim/issues/27#issuecomment-52159026).

**Comment by rszabo** [comment]
@StanAngeloff  Yes, sorry about being away. I implemented many of those as I wrote, but failed to go upstream. Either way, they were working fine but somewhere along the neovim updates they broke, and figured maybe you saw any immediate errors.

**Comment by StanAngeloff** [comment]
Mm, interesting, other than a line for the missing `syn match phpStaticSelector` I can't see anything wrong with those matches. The syntax should be compatible with Neovim (albeit I don't use it very often and not an expert).

**Comment by rszabo** [comment]
```
syn match phpStaticSelector "::" contained display
```

I'd love to provide a pull request of some changes in the near future.
