### ISSUE TITLE
Namespace highlight

### ISSUE THREAD

**Issue by rafi** [StanAngeloff/php.vim#31]
Is it possible to highlight a namespace?
I've been using this to highlight backslashes: `syn match phpParent "\\" contained` .. but that's not too smart.

Thank you very much for your work.

**Comment by StanAngeloff** [comment]
As part of #45 and once merged you should be able to specify different highlighting for the class/namespace following `use`. If anyone is interested to refactor the code to add support for `namespace` as well, please send over a pull request and I'll gladly review & accept.

Archiving discussion.

**Comment by tam5** [comment]
@StanAngeloff I agree with:

@swekaj 's
> I do think it could be nice to highlight the \ separator, though. That would make longer namespaces easier to read.

Is there a way to accomplish this currently?

Btw thanks for all your work!
