### ISSUE TITLE
highlight about `::`

### ISSUE THREAD

**Issue by gaohaoliang** [StanAngeloff/php.vim#35]
I was looking for `::` highlight, 
such as
```
    Yii::$app
    Yii::SOME_CONST
    Yii::$app()
    Yii::app()
````

But, at now the syntax file did not provide these feature yet.
here are my some changes, hopping these can be helpful.
```
syn match phpMethodsVar "\(->\|::\)\$\=\h\w*" contained contains=phpMethods,phpMemberSelector display
syn match phpMemberSelector "->\|::"  contained display
```

**Comment by StanAngeloff** [comment]
Thank @gaohaoliang, tweaked and committed. Happy New Year :sparkles:
