### ISSUE TITLE
use function (PHP 5.6) should not be phpFunction

### ISSUE THREAD

**Issue by sekjun9878** [StanAngeloff/php.vim#42]
Hello,

When I type `use function Vendor\Package\function` php.vim thinks of the Vendor string as a phpFunction, presumably because it's a `function Vendor`. Maybe a negative lookbehind?

**Comment by StanAngeloff** [comment]
Thanks for the issue report. An alternative approach may be to blacklist function highlighting within `use` statements.

**Comment by StanAngeloff** [comment]
Moving discussion over to _#45 Support "use function" properly_.
