### ISSUE TITLE
Windows Style CR-LF line endings after updating syntax file. 

### ISSUE THREAD

**Issue by iwyg** [StanAngeloff/php.vim#43]
`php.vim` gets corrupted with windows style line endings after updating the syntax file via docker. 

Vim reports error 

```
E492: Not And Editor Command: ^M
```

![vim error](https://dl.dropboxusercontent.com/u/17036738/github/issues/vim_err_e492.png)

**Comment by StanAngeloff** [comment]
Did you pipe the output through `sed` as shown in the README?

```
[..] | sed 's/\x0D$//'
```

This should get rid of the nasty Windows line-endings.

What OS are you using?

**Comment by iwyg** [comment]
Yes I did. I'm using OS X 10.11.1

**Comment by StanAngeloff** [comment]
Updated README with further instructions on Docker's usage.
