### ISSUE TITLE
internal functions and constants not being highlighted

### ISSUE THREAD

**Issue by iwyg** [StanAngeloff/php.vim#44]
Any hint why this would happen?
![php vim syntax](https://dl.dropboxusercontent.com/u/17036738/github/issues/php-vim-syntax.png)

I've tried different colorschemes + disabled all plugins but php-vim but to no avail. 
Thanks

**Comment by iwyg** [comment]
Hm seems to be a caching problem on my side.

**Comment by StanAngeloff** [comment]
Would you mind sharing that piece of code as text as well as what exactly had gone wrong? I wouldn't mind checking on my machine to make sure it's all good indeed. Thanks.

**Comment by iwyg** [comment]
It was my fault. I had a defined list of `php_syntax_extensions_enabled` in my vimrc that would cause the issue. 
However, I noticed that the easytags plugin messes with syntax highlighting when setting 
```vim
let g:easytags_events = ['BuffWritePost']
```
and I have no idea why.
