### ISSUE TITLE
Undefined variable: main_syntax

### ISSUE THREAD

**Issue by wjagodfrey** [StanAngeloff/php.vim#50]
Quite often when switching to a php buffer, I get this error:
```
Error detected while processing /Users/wgodfrey/dotfiles/vim/bundle/php.vim/syntax/php.vim:
line  850:
E121: Undefined variable: main_syntax
E15: Invalid expression: main_syntax == 'php'
```
I'm really not sure what to make of it but it's quite frustrating. Closing and reopening vim seems to fix it. If you need any more information please ask.

**Comment by StanAngeloff** [comment]
Do you run the latest version of php.vim? Do you have any specific bundles/plugins for HTML?

If you are comfortable editing your vimfiles, can you update line 850 of `syntax/php.vim` to:

```vim
if (exists("main_syntax") && main_syntax == 'php')
```

Run Vim for a while, are any errors reports?

**Comment by wjagodfrey** [comment]
I'll give it a go and get back to you, thanks Stan

**Comment by wjagodfrey** [comment]
@StanAngeloff That seems to fix the problem. Removed it and it came back, put it back in and it went away.
