### ISSUE TITLE
PHP closing tag in DocBlock

### ISSUE THREAD

**Issue by janhenkgerritsen** [StanAngeloff/php.vim#51]
If you have a PHP closing tag in a DocBlock comment syntax highlighting will go wrong after that closing tag. 

An example of such a DocBlock:

```
    /** 
     * Disable middleware for the next requests.
     *
     * ``` php
     * <?php
     * $I->disableMiddleware();
     * ?>
     * ``` 
     */  
```

These types of DocBlocks are used by [Codeception](https://github.com/Codeception/Codeception) to document the behavior of modules.

**Comment by StanAngeloff** [comment]
Ah this is nasty. The Vim region ends regardless of the comment block. This doesn't happen in a string so there's a way around it. Leaving open to investigate.

**Comment by StanAngeloff** [comment]
Do you mind editing your `syntax/php.vim` by hand and adding the keyword `extend` preceded by a space on the line containing `SynFoldDoc syn region phpDocComment`?

That should be around line 598 +/- a couple of lines. The full line will then read:

```vimscript
  SynFoldDoc syn region phpDocComment   start="/\*\*" end="\*/" keepend contains=phpCommentTitle,phpDocTags,phpTodo,@Spell extend
```

Do you see any weird issues in your PHP files after this change?

**Comment by janhenkgerritsen** [comment]
That fixes my problem and it does not seem to affect anything else.

Thanks for looking into it!

**Comment by StanAngeloff** [comment]
I'll let this one sit for a few days to give you and me the chance to run with the modified code before releasing in the repository for everyone else.

You may encounter a conflict once merged, hopefully if you haven't made any more changes it's a straightforward replace with the upstream version.
