### ISSUE TITLE
Php7 syntax support

### ISSUE THREAD

**Issue by hoenirvili** [StanAngeloff/php.vim#52]
When you will add php7 support syntax?

**Comment by StanAngeloff** [comment]
What are you missing? Do you have any example files with bad highlighting

**Comment by hoenirvili** [comment]
Sorry didn't know that it supports also 7.0 implicitly.
" syntax/php.vim
" Language: PHP 5.3 & up

Btw I'm having a little trouble installing it. I run the php generator I added both php.vim and the output.vim in syntax dir from my vim and I'm getting this error.

```vim
"/srv/http/cn/ajax/ajax.php" [noeol] 28L, 767C                                                                                                                               
Error detected while processing /home/hoenir/.config/nvim/syntax/php.vim:                                                                                                    
line   63:                                                                                                                                                                   
E108: No such variable: "b:current_syntax"    
```

**Comment by StanAngeloff** [comment]
See #50 seems like it's more widespread than I thought.

**Comment by Taluu** [comment]
Hello,

There is something from php7 that does not seem to be supported, it's the `yield from generator()`. The `from` is not colored, but it doesn't really matter. :D

I didn't try the new features though.
