### ISSUE TITLE
CONST value as array (PHP 7)

### ISSUE THREAD

**Issue by mayppong** [StanAngeloff/php.vim#54]
In PHP 7, you can now use expressions as class constants. However, the syntax checker is still complaining.
```
Plinth/src/Contact/Address.php|24 error| Arrays are not allowed in class constants
```

I would love to see the the plugin support this.

**Comment by StanAngeloff** [comment]
Hi,

Do you have [Syntastic](https://github.com/scrooloose/syntastic) installed as well? The php.vim plug-in does not provide any linting by default.

**Comment by mayppong** [comment]
I do. I was under the impression that Syntastic uses this plugin for the underlying linting.

**Comment by StanAngeloff** [comment]
Syntastic will defer to the `php` executable for linting and `phpcs` / `phpmd` for further analysis when configured. This plug-in does syntax highlighting only and does not provide linting.

You may be able to resolve your issue by upgrading the PHP version installed on your computer (be careful when doing so as it may break other things). Arrays in class constants are supported in [PHP 5.6+](http://php.net/manual/en/migration56.new-features.php#migration56.new-features.const-scalar-exprs).
