### ISSUE TITLE
Detect functions and constants heuristically

### ISSUE THREAD

**Issue by msjyoo** [StanAngeloff/php.vim#55]
For example, if a constant is in all upper case letters, then there should be an option to consider it as a constant and apply syntax to it accordingly.

Similarly to functions e.g. func( with bracket could be considered a function (phpUserFunc and phpUserConst)?

**Comment by VonHeikemen** [comment]
Using the syntax override method suggested on the readme, one could do this to highlight function calls.

```vim
function! PhpSyntaxOverride()
  syn match phpFunctionCall /\v\h\w*\ze(\s?\()/ 
    \ containedin=phpRegion,phpIdentifier
 
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END
```
I'm sure there is a better way to do it inside the plugin itself.
