### ISSUE TITLE
Indendation broken in comment blocks

### ISSUE THREAD

**Issue by mikehaertl** [StanAngeloff/php.vim#56]
I found a problem when adding a linebreak inside an existing comment block. It only happens, if the first comment line starts with an `@` like in `@return` or `@param`.

Here's an example:

![vim-php-before-linebreak](https://cloud.githubusercontent.com/assets/675062/15857225/880585dc-2cba-11e6-91d6-e1f1d2ec4c99.png)

As you see the cursor is right after "an". If I now enter insert mode and add a line break, it breaks indentation of the comment lines:

![vim-php-after](https://cloud.githubusercontent.com/assets/675062/15857246/a3d97b92-2cba-11e6-9a8f-ba58b194197b.png)

**Comment by StanAngeloff** [comment]
This issue reminds me of #58. Closing and archiving this conversation.
