### ISSUE TITLE
Indentaion broken for some words

### ISSUE THREAD

**Issue by mikehaertl** [StanAngeloff/php.vim#58]
I tried to create a list like:

``` php
<?php
$a = [
    'ab',
    'cd',
    'no',
    'xy',
];
```

After typing `'no',` and pressing enter, the auto-indenting is broken. The cursor is now position in the 1st column:

![vim-linebreak-no](https://cloud.githubusercontent.com/assets/675062/16041490/eba74f32-3235-11e6-9d96-c85019416a89.png)

It seems like `no` is matching some keyword in the syntax plugin.

**Comment by mikehaertl** [comment]
@StanAngeloff Will you find time to look into this? I found even more oddities with indenting, especially when mixing HTML with PHP. I'd provide a PR if I could - but then I'd have to learn some vimscript first and study the existing code. My hope was that I can avoid that. But if you're too occupied maybe I'd give it a try because the current situation is quite annoying. I'm not sure, but I feel like the plugin was behaving a little better in earlier versions. Right now it sometimes tops indenting completely at some point.

**Comment by StanAngeloff** [comment]
@mikehaertl Unlikely to be able to address the indentation issues any time soon. I'm pretty happy with it myself and albeit it chokes up in a few places, generally it behaves correctly for me.

My expectation is that the current highlighting groups don't match up with what [2072/PHP-Indenting-for-VIm](https://github.com/2072/PHP-Indenting-for-VIm) is [expecting](https://github.com/2072/PHP-Indenting-for-VIm/blob/master/indent/php.vim#L917). A PR may be better addressed in that repo, although I can't say if @2072 is interested in supporting this repository. His indentation plug-in is incorporated in the official Vim package.

**Comment by mikehaertl** [comment]
@StanAngeloff Thanks for the pointers - I was not ware of this other plugin. It leaves me little confused now about how syntax highlighting and indentation relate to each other. So are you basically saying, that indentation is not really part of your plugin here? But if it is, then how does it play together with the other plugin you linked to?

**Comment by StanAngeloff** [comment]
You are correct, indentation is not strictly part of this plug-in. The linked plug-in inspects various aspects of the syntax highlighting to make decisions as how to indent code. When introducing new syntax highlighting groups (e.g., bold for first sentence of a docblock), these groups need to be supported by the indentation plug-in, too.

How best to achieve this, I have not quite worked out.

**Comment by mikehaertl** [comment]
Ok, thanks for clarifying. I've now updated to the latest indentation plugin and it seems to already improve the situation. But will have to use it a little longer before I can really say if things are better.

Feel free to close these issues if you think they should not to be fixed here.
