### ISSUE TITLE
Match argument function

### ISSUE THREAD

**Issue by rodrigore** [StanAngeloff/php.vim#59]
I would like to have some group to match the argument of the function definition, in order to make them italic, something like this:
```
hi! phpFunctionArgs gui=italic cterm=italic
```

**Comment by StanAngeloff** [comment]
Thank you for taking the time to suggest this enhancement.

The request is outside the scope of this plug-in. To distinguish function arguments from ordinary parentheses would require knowledge of the code structure. This plug-in does not implement that.
