### ISSUE TITLE
Does this follow psr standards?

### ISSUE THREAD

**Issue by mayurpande** [StanAngeloff/php.vim#60]
Hi sorry if this is a silly question I have been using vundle for some time with another php plugin for html indenting as well.

However each time I try to change the .vimrc file it won't let me change tabs to space to comply with psr-2. 

Will this package let me do that? Also will it provide html indenting as well (or even maybe twig files as well?)

**Comment by StanAngeloff** [comment]
This plug-in provides syntax highlighting only and won't mess with your indentation settings.

HTML indenting is available in PHP files, but relies on the default Vim syntax highlighting. Twig is not available, you'll need to find a suitable plug-in to highlight Twig templates.
