### ISSUE TITLE
Indentation doesn't work when syntax is off

### ISSUE THREAD

**Issue by wayneashleyberry** [StanAngeloff/php.vim#61]
I thought this might be a vim limitation, but when I have syntax off indentation works fine for javascript and Go.

With syntax off, indentation using the `=` key or using `o` to enter a new line doesn't indent at all.

**Comment by StanAngeloff** [comment]
How did you reproduce this? Did you turn if off with `:syntax off<CR>`?

What use case do you have for preserving indentation, but turning the syntax off?

**Comment by wayneashleyberry** [comment]
Yeah, by default my syntax is on... I used `:syntax off` to disable it. My use case is that I'm starting to leave syntax off in terminal vim for performance reasons. This really wouldn't bother me if not for finding other languages seem to work fine.

If you consider the following code:

```php
<?php

function test() {
}
```

When my cursor is over `function` and I hit `o`, with syntax on my cursor moves here:

```php
function test() {
    |
}
```

After disabling syntax and trying the same thing my cursor moves here:

```php
function test() {
|
}
```

**Comment by StanAngeloff** [comment]
There isn't anything in this plug-in that relates to indentation. There are various hooks for folding. I wonder if another Vim built-in plugin relies on syntax groups being defined to perform the indentation?

**EDIT*: Looks like [this is the case](https://github.com/2072/PHP-Indenting-for-VIm/blob/master/indent/php.vim#L20).

**Comment by wayneashleyberry** [comment]
That's it @StanAngeloff! I'll add an issue over there - thanks :)
