### ISSUE TITLE
Colorizing parenthesis

### ISSUE THREAD

**Issue by vivoconunxino** [StanAngeloff/php.vim#63]
Hi, I'd like to assign a custom colour to the parenthesis, but I can't find the way to do it.

I've tried this on my vimrc:
autocmd BufRead,BufNewFile \* syn match parens /[(){}]/ | hi parens ctermfg=red

also putting at the bottom of my vimrc:

function! PhpSyntaxOverride()
    syn match parens /[(){}]/ | hi! parens ctermfg=blue
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END

Nothing.. no way to change it. Any hint please?

**Comment by StanAngeloff** [comment]
Try with the following instead:

```vimscript
syn match phpParentOnly "[()]" contained containedin=phpParent
hi phpParentOnly guifg=#f08080 guibg=NONE gui=NONE
```
