### ISSUE TITLE
Performance issues in a file with single comment

### ISSUE THREAD

**Issue by stormherz** [StanAngeloff/php.vim#66]
I was having heavy performance issues and overall slowness in my php files so I've excluded plugins one by one to pinpoint the cause of it. After disabling php.vim everything came back to normal.

Here is a sample file, which is very slow in opening and moving around on my machine with plugin enabled:

```php
<?php

// jjjjjjjjjjjjjjjjjjjjjjjjjjfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffff



```

My envirnoment:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 12 2017 03:04:35)
MacOS X 10.12.2 (16C67)
Included patches: 1-172

Let me know if you need profiling logs or anything like that =)

**Comment by StanAngeloff** [comment]
I get this as well, although after disabling everything I could think of in the highlighting, Vim is still slow to work in a file containing a long comment line.

I tried pasting the same line in a `.js` file and that yielded abysmal editing speeds, too.

It seems like [Vim is just too slow](http://superuser.com/a/302188) with (very long lines)[http://stackoverflow.com/a/3460872].

Can you confirm if you are experiencing similar issues editing long lines using a different syntax, e.g., XML?

**Comment by stormherz** [comment]
Hm, tried with js and xml - vim is getting slower, yes, but not that much, the usual slowness =)
I don't think there is a underlying bug indeed in php.vim, because, yeah, we all now how vim terribly handles long lines when highlighting is involved, just thought to let you know that with enabled php.vim editor is getting slower in php files, but that can be subjective, I guess.
And it's just a bad practice to have such long lines in code anyway =)

**Comment by Techwolf12** [comment]
I've tested it with other syntax plugins but none of those slows vim down as much as this plugin does. I do believe there is a lot to be optimized in this plugin.

**Comment by StanAngeloff** [comment]
@Techwolf12 I agree.

**Comment by StanAngeloff** [comment]
The culprit seems to be #68 [phpHereDoc regexp](https://github.com/StanAngeloff/php.vim/issues/68). If you set this in `vimrc`, editing becomes _fast_ again:

```vimscript
let php_html_load=0
let php_html_in_heredoc=0
let php_html_in_nowdoc=0

let php_sql_query=0
let php_sql_heredoc=0
let php_sql_nowdoc=0
```

Use #68 to continue the discussion.
