### ISSUE TITLE
Docblock inside function breaks highlighting

### ISSUE THREAD

**Issue by char101** [StanAngeloff/php.vim#73]
Hi,

This happens with the default syntax file and with this plugin too.

Example code

```php
<?php

function test()
{
    /* @var */
    echo 'test';
}
```

How it looks in Vim

![2017-12-09 13_24_38- no name - gvim16](https://user-images.githubusercontent.com/71255/33793150-5855a9d0-dce4-11e7-9385-0269a3fda1e2.png)

**Comment by StanAngeloff** [comment]
I was unable to reproduce.

1. What is the `filetype` detected by Vim (`:echo &ft<CR>`)?
2. How many maximum columns have you configured (`:echo &synmaxcol<CR>`)?
3. Did you try re-opening the file?
4. Do you have a `vimrc` online?

**Comment by lvht** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/2030591/34091518-13004c16-e3f9-11e7-956e-f7b55d496aaf.png)

And I am using the NeoVim.

**Comment by StanAngeloff** [comment]
@lvht I don't see anything going wrong with your highlighting, what does it look like without the docblock?

**Comment by lvht** [comment]
After I disable php.vim, it looks like
![image](https://user-images.githubusercontent.com/2030591/34101437-ba26d63c-e420-11e7-95d7-3cd48f9f8183.png)

**Comment by StanAngeloff** [comment]
@lvht Can you screenshot with `php.vim` enabled, but the docblock removed from code, so it should be the class followed by the method, no comments anywhere in the code.

**Comment by lvht** [comment]
The issue is `php.vim` cannot highlight the `@inheritDoc` annotation in the docblock.

**Comment by lvht** [comment]
![image](https://user-images.githubusercontent.com/2030591/34101999-821a9b64-e422-11e7-887d-2dc5e2cdecdf.png)
@StanAngeloff

**Comment by lvht** [comment]
I use the `jacoborus/tender.vim` theme.

**Comment by StanAngeloff** [comment]
| php.vim | ~ |
| -- | -- |
| ![](https://user-images.githubusercontent.com/2030591/34091518-13004c16-e3f9-11e7-956e-f7b55d496aaf.png) | ![](https://user-images.githubusercontent.com/2030591/34101999-821a9b64-e422-11e7-887d-2dc5e2cdecdf.png)

I'm blind to the difference, can you point it out for me please?

**Comment by StanAngeloff** [comment]
> The issue is php.vim cannot highlight the @inheritDoc annotation in the docblock. @StanAngeloff

I see. There is actually a different highlighting group for that, try defining a colour for `phpDocTags`.

**Comment by lvht** [comment]
@StanAngeloff Please focus on the docblock comment of method `hi`.

In my opinion, php.vim should highlight the `@inheritDoc` in the docblock like
![image](https://user-images.githubusercontent.com/2030591/34103079-6a778c20-e426-11e7-9b3c-0ff4b19b6ea3.png)

**Comment by lvht** [comment]
> This appears unrelated to the issue described initially.

But it does!
Without php.vim
![image](https://user-images.githubusercontent.com/2030591/34103135-9a98face-e426-11e7-8a31-fa47166c5d83.png)

And with php.vim
![image](https://user-images.githubusercontent.com/2030591/34103181-ca57bfe8-e426-11e7-8d71-bf899ed8c702.png)

The `@var` is not highlighted.

**Comment by StanAngeloff** [comment]
@lvht Did you try overriding the `phpDocTags` match as above?

```vim
hi phpDocTags guifg=#f08080 guibg=NONE gui=NONE
```

**Comment by StanAngeloff** [comment]
If you [have followed the `README`](https://github.com/StanAngeloff/php.vim#overriding-highlighting), you may already have an overriding function. Make sure to disable / remove it or customise the colours to your liking.

**Comment by lvht** [comment]
Thank you. Use `phpSyntaxOverride` works.
