### ISSUE TITLE
Syntax Not Working

### ISSUE THREAD

**Issue by alby6** [StanAngeloff/php.vim#75]
Hello,

I tried to use this plugin, and it successfully installed when i typed :PlugInstall.

However, nothing happens when I make an error in php. I've read the readme multiple times.

Is there something I'm missing? I'm using vim 8, php 7.1.7
Edit:
I tried

let g:php_syntax_extensions_enabled = ["bcmath", "bz2", "core", "curl", "date", "dom", "ereg", "gd", "gettext", "hash", "iconv", "json", "libxml", "mbstring", "mcrypt", "mhash", "mysql", "mysqli", "openssl", "pcre", "pdo", "pgsql", "phar", "reflection", "session", "simplexml", "soap", "sockets", "spl", "sqlite3", "standard", "tokenizer", "wddx", "xml", "xmlreader", "xmlwriter", "zip", "zlib"]

But nothing happens

**Comment by StanAngeloff** [comment]
This is a syntax plug-in. It does not perform syntax checking, though, just colouring. Try NeoMake, Ale or Syntastic instead.

**Comment by alby6** [comment]
Thanks for the response!!! Sorry for my misunderstanding.
