### ISSUE TITLE
Cleanup the syntax.ini file ?

### ISSUE THREAD

**Issue by Taluu** [StanAngeloff/php.vim#80]
Hello there.

Some things should be cleaned up from the syntax file, such as deprecated / removed extensions (`mcrypt`, `mysql`, ...), and maybe updated ?

When launching the script to update the php.vim, I think it would be better to lookup all the enabled extensions and then generate the right syntax from this rather than relying on a syntax.ini file.

**Comment by Taluu** [comment]
For that, we could rely on the [`get_loaded_extensions()`](http://php.net/manual/fr/function.get-loaded-extensions.php) and [`get_extension_funcs`](http://php.net/manual/fr/function.get-extension-funcs.php), which could also allow us to not depend on reflection (who cares though, as the script shouldn't be often run...)

**Comment by StanAngeloff** [comment]
Sounds like a good idea. The current syntax update script is intended to be ran by the maintainer (myself). It runs in a Docker container with all extensions installed (granted some obsolete ones are not included). The idea is to have the syntax file include ALL possible extensions and let the user decide which ones to include using `g:php_syntax_extensions_enabled`.

It would be neat to have a command which configures `g:php_syntax_extensions_enabled` for you auto-magically based on what extensions are reported by `get_loaded_extensions()`.

**Comment by akrabat** [comment]
In my case, I have extensions loaded inside vagrant & docker that aren't loaded on my local computer, so I quite like having syntax for all all extensions available.
