### ISSUE TITLE
Incorrectly associated group

### ISSUE THREAD

**Issue by dsifford** [StanAngeloff/php.vim#81]
Hi there.

Great work on this syntax! Super robust!

One small little gripe I have that I'm hoping you might consider is the following:

https://github.com/StanAngeloff/php.vim/blob/9f2d8fb0030684af53f30a6e532289948e83facc/syntax/php.vim#L525-L526

Shouldn't this group instead be `phpKeyword`? You literally use the word `keyword` in your comment describing it.

Thanks for considering

**Comment by StanAngeloff** [comment]
Thanks for poking around in the syntax file! I'm merely looking after the great work done by others as can be [seen in the header comment](https://github.com/StanAngeloff/php.vim/blob/9f2d8fb0030684af53f30a6e532289948e83facc/syntax/php.vim#L9).

Unfortunately making this change may [break users syntax colouring or overrides](https://github.com/search?l=Vim+script&q=phpType&type=Code).

**Comment by dsifford** [comment]
@StanAngeloff I'm not sure what you mean by "the change might break users syntax coloring overrides".

To clarify: My claim is that the group that exists right now is _currently_ breaking **everybody's** syntax coloring. This is a clear violation of syntax as the words `public`, `private`, `protected`, etc _are_ language keywords and should be treated as language keywords.

So the notion that we should keep as-is because people have put guards in place already to cover this break is not valid. It should most definitely be fixed here.

I just tried in a clone of this repo and making the changes suggested in my PR fix this completely and align the syntax similarly to all other vim syntaxes that use these types of keywords.

**Comment by dsifford** [comment]
This is a big deal particularly because this repo is the syntax used by [vim-polyglot](https://github.com/sheerun/vim-polyglot) so there's not a super easy way to fix this without convincing the polyglot maintainers to choose a different fork.

**Comment by StanAngeloff** [comment]
But they are keywords, i.e., `syn keyword`? The group name is arbitrary.

**Comment by StanAngeloff** [comment]
Perhaps the confusion is coming from the fact that phpType is linked to Type and not Keyword?

**Comment by dsifford** [comment]
The syntax coloring from themes stems from the group it's allocated to... The `keyword` parameter doesn't have any meaning except to vim it states that the list of words should be treated as a list of words, and not regexps.

So, in other words: To the outside world, vim treats those words as "types", and not keywords. 

Does that make sense?

**Comment by dsifford** [comment]
Put simply: Right now, those words have the syntactical scope of "type" and not "keyword"

**Comment by StanAngeloff** [comment]
As above, perhaps the confusion is coming from the fact that `phpType` is linked to `Type` and not `Keyword`. I'm not inclined to make the change as it will break existing syntax highlighting.

The README has a section on how to add overrides, adding this should suffice:

```vim
" Put this function at the very end of your vimrc file.

function! PhpSyntaxOverride()
  hi! link phpType Keyword
endfunction

augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END
```

**Comment by dsifford** [comment]
I understand where you're coming from, but the syntax **is already broken**. That's the point.

Users 100% should not have to put in "overrides" for bugs. This is something that needs to be handed here.

If you are adamant about not fixing this, I'll be opening an RFC in vim-polyglot to move off of this fork. 

This is absolutely _stunning_ to me.

**Comment by StanAngeloff** [comment]
Thank you for your input. If this is a deal-breaker for you or vim-polyglot, please feel free to fork and maintain a copy with your updates :+1:

**Comment by dsifford** [comment]
Will do. Thanks

**Comment by sheerun** [comment]
Could the solution be to duplicate this line instead of removing it?

**Comment by sheerun** [comment]
Totally understand. Usually it's the opposite - plugins break compatibility while core vim syntaxes are more stable. I think it would be reasonable to configure vim-polyglot to ship what newest vim is shipping then.
