### ISSUE TITLE
Add note about Debian/Ubuntu syntax file

### ISSUE THREAD

**Issue by mikehaertl** [StanAngeloff/php.vim#87]
I just found that on my Ubuntu (Debian) box there's now yet another PHP syntax file included in the vim package:

https://jasonwoof.com/gitweb/?p=vim-syntax.git;a=blob;f=php.vim;hb=HEAD

In contrast to the "old" vim.org version it seems like this one is also actively maintained, just like yours.

Could you maybe add a note (or even a feature comparison list?) of the two versions to the README?

I know, that this request may sound odd. But from a quick look it's not so easy to find which is better. So any help on making that decision would really help out the poor PHP developer.

**Comment by StanAngeloff** [comment]
I'm afraid I haven't explored the Debian version in details and cannot comment. I'll leave this open for others to chime in.

**Comment by mikehaertl** [comment]
Forgive my lazyness - I was just hoping you already knew that file.

Meanwhile I had a closer look and think your version offers way more configuration options, so I'll keep on using that. I didn't compare all the details though.
