### ISSUE TITLE
on BufEnter not higglight

### ISSUE THREAD

**Issue by marlonfan** [StanAngeloff/php.vim#88]
I'm use neovim, version is 0.3.1

on open a php file, highlight is invalid

![before](https://files.gitter.im/neoclide/coc.nvim/EM3O/image.png)

then,  execute ``:syntax sync fromstart`` command, highlight is recover

![after](https://files.gitter.im/neoclide/coc.nvim/24nm/image.png)

**Comment by marlonfan** [comment]
Now, i'm write a autocmd ``autocmd BufEnter *.php :syntax sync fromstart`` solve the problem temporarily

**Comment by marlonfan** [comment]
maybe because my code has "?>" ?

**Comment by StanAngeloff** [comment]
You can play around with `php_minlines` and `php_sync_method`.

```vim
"  php_sync_method = x
"                    x=-1 to sync by search ( default )
"                    x>0 to sync at least x lines backwards ( use php_minlines )
"                    x=0 to sync from start
```

**Comment by marlonfan** [comment]
Thank you! Solved my problem. But is this problem a bug or a defect? Is there a better solution?
