### ISSUE TITLE
Unable to clone with fsck enabled

### ISSUE THREAD

**Issue by magikid** [StanAngeloff/php.vim#96]
I am unable to clone this repo without changing my configuration.  Here is a video of the issue:
![demo](https://user-images.githubusercontent.com/115515/73575462-3ffa7700-4446-11ea-87fd-4e0bac3b3fb4.gif)

After cloning the repo, I ran `git fsck --full` and it seems that two commits have incorrect timezone information.

```
😎  λ ~/php.vim/ master git fsck --full
Checking object directories: 100% (256/256), done.
error in commit 0148af066879d32d7ffe8400c0910020c60b1ce1: badTimezone: invalid author/committer line - bad time zone
error in commit 09ddf308e352c88c524df93761848038b087707c: badTimezone: invalid author/committer line - bad time zone
Checking objects: 100% (637/637), done.
🔥  λ ~/php.vim/ master
```

Checking the commits, they do indeed have bad timezones. 

```
😎  λ ~/php.vim/ master git cat-file -p 09ddf308e352c88c524df93761848038b087707c
tree 768e2f82de6da85d1d3828d9fe264fc044c3530b
author Paul Garvin <paul@paulgarvin.net> 1259452800 +0000
committer Able Scraper <scraper@vim-scripts.org> 1287367363 -700

Version 1.0: Initial upload
```

You can see from the output from `git cat-file` that the timezone offset for the committer is `-700`.  It should probably be `-0700`.

Unfortunately, I don't have a good suggestion on how to fix this error other than rewriting the history.

**Comment by StanAngeloff** [comment]
Ah, those commits seem to be coming from the original repository which was forked. Unfortunately I'm not going to go back and rewrite the commit history and recreate all following commits.

I'll add a line to the README to clarify how to clone the repository in one go:

```sh
git clone -c fetch.fsckObjects=false git@github.com:StanAngeloff/php.vim.git
```
